import createClient from "openapi-fetch";

import type { paths } from "./schema";

// Single typed transport instance. Every request the app makes goes through
// this client, which is fully typed from the backend's OpenAPI document
// (`paths` is generated by `openapi-typescript`).
//
// `baseUrl` defaults to the relative "/api" path which the Vite dev server
// proxies to the backend (see vite.config.ts) to sidestep CORS.
const baseUrl = import.meta.env.VITE_API_BASE_URL || "/api";

export const apiClient = createClient<paths>({ baseUrl });
